services:
  jellyrequest:
    build: https://github.com/mvanhare/jellyrequest.git
    container_name: jellyrequest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data